lr1
ijustseeblood/BSUIR-Software-Design-2020 pull request #1
Opened 2021-01-05 09:42 UTC by ijustseeblood

2021-01-06 10:20 UTC, gmltA requested changes
See task requirements.

2021-01-06 14:25 UTC, ijustseeblood commented
I've also added git tag

2021-01-07 11:19 UTC, gmltA requested changes
Some requirements are not fulfilled.

2021-01-07 16:29 UTC, gmltA commented on Converter/autoVersion.gradle
> +    }
When this branch will be executed?

2021-01-07 17:20 UTC, ijustseeblood commented on Converter/autoVersion.gradle
> +    }
It will be executed, if the version name does not contain the '-' symbol, for example "1.2". Then it would only take the minor version number from the string and save the patch number as zero.

2021-01-07 17:59 UTC, gmltA commented on Converter/autoVersion.gradle
> +    }
And what should I do with the repository to achieve this?

2021-01-07 22:44 UTC, ijustseeblood commented on Converter/autoVersion.gradle
> +    }
The command "git describe" is getting the most recent tag. If the tag points to the commit, then only the tag is shown. Otherwise, it suffixes the tag name with the number of additional commits on top of the tagged object and the abbreviated object name of the most recent commit. So, if it is the fist tag on the branch or if there have been no commits after the last tag added, we would need this else case, because the "git describe" command is going to return v1.6 (for ex.) instead of v1.6-8-*something*.

2021-01-08 10:51 UTC, gmltA approved these changes

2021-01-08 11:34 UTC, merged